/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("./reception.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Containersockel"
        geometry={nodes.Containersockel.geometry}
        material={materials["Material.937"]}
        position={[15.86, 1.79, 62.41]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Fundament11_1"
        geometry={nodes.Fundament11_1.geometry}
        material={materials["Material.267"]}
        position={[-8.62, 1.7, 30.97]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Fundament_1_remesh001"
        geometry={nodes.Fundament_1_remesh001.geometry}
        material={materials.floor}
        position={[-2.39, 0.43, 19.58]}
      />
      <mesh
        name="Fundament_1_remesh002"
        geometry={nodes.Fundament_1_remesh002.geometry}
        material={materials["Material.265"]}
        position={[-0.5, 1.74, -38.69]}
      />
      <mesh
        name="Cuve"
        geometry={nodes.Cuve.geometry}
        material={materials["Material.318"]}
        position={[1.19, 33.97, -1.21]}
      />
      <mesh
        name="CuveSockel"
        geometry={nodes.CuveSockel.geometry}
        material={materials["Material.265"]}
        position={[1.19, 1.58, -1.21]}
      />
      <mesh
        name="R08474_Losflansch_DN250-PN10-d2730-144041_1003"
        geometry={
          nodes["R08474_Losflansch_DN250-PN10-d2730-144041_1003"].geometry
        }
        material={materials["Material.318"]}
        position={[1.17, 3.8, 20.94]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.1}
      />
      <mesh
        name="R08474_Losflansch_DN250-PN10-d2730-144041_1"
        geometry={nodes["R08474_Losflansch_DN250-PN10-d2730-144041_1"].geometry}
        material={materials["Material.318"]}
        position={[1.17, 11.74, 21.51]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        name="R08756_Blindflansch_DN200-PN10_14404111_2"
        geometry={nodes["R08756_Blindflansch_DN200-PN10_14404111_2"].geometry}
        material={nodes["R08756_Blindflansch_DN200-PN10_14404111_2"].material}
        position={[1.19, 49.48, -1.24]}
        rotation={[-Math.PI / 2, 0, 1.57]}
      />
      <mesh
        name="R08474_Losflansch_DN250-PN10-d2730-144041_1002"
        geometry={
          nodes["R08474_Losflansch_DN250-PN10-d2730-144041_1002"].geometry
        }
        material={materials["Material.318"]}
        position={[1.17, 3.8, 21.56]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.1}
      />
      <mesh
        name="Circle002"
        geometry={nodes.Circle002.geometry}
        material={nodes.Circle002.material}
        position={[1.2, 47.68, -1.22]}
      />
      <mesh
        name="Circle"
        geometry={nodes.Circle.geometry}
        material={nodes.Circle.material}
        position={[1.2, 11.74, 19.3]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Circle001"
        geometry={nodes.Circle001.geometry}
        material={nodes.Circle001.material}
        position={[1.2, 3.78, 19.3]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="ELEVATION_BLINDFLANSCH_DN800PRT(2)_1"
        geometry={nodes["ELEVATION_BLINDFLANSCH_DN800PRT(2)_1"].geometry}
        material={materials["Material.445"]}
        position={[-18.92, 4.52, -9.61]}
        rotation={[Math.PI / 2, 0, 0.41]}
      />
      <mesh
        name="ELEVATION_ZARGE_8410PRT_1001"
        geometry={nodes.ELEVATION_ZARGE_8410PRT_1001.geometry}
        material={materials["Material.446"]}
        position={[-18.06, 4.51, -9.5]}
        rotation={[0, 1.16, 0]}
      />
      <mesh
        name="Circle003"
        geometry={nodes.Circle003.geometry}
        material={nodes.Circle003.material}
        position={[-18.43, 4.54, -9.67]}
        rotation={[0, -0.4, -Math.PI / 2]}
      />
      <mesh
        name="Circle004"
        geometry={nodes.Circle004.geometry}
        material={nodes.Circle004.material}
        position={[-4.69, 23.31, -23.66]}
      />
      <mesh
        name="Circle005"
        geometry={nodes.Circle005.geometry}
        material={nodes.Circle005.material}
        position={[-2.04, 23.31, -24.37]}
      />
      <mesh
        name="Lamellenstopfen_ID_411_111_1"
        geometry={nodes.Lamellenstopfen_ID_411_111_1.geometry}
        material={materials["Material.244"]}
        position={[-4.69, 45.89, -23.66]}
        rotation={[Math.PI / 2, 0, 0.7]}
      />
      <mesh
        name="R08474_Losflansch_DN250-PN10-d2730-144041_1001"
        geometry={
          nodes["R08474_Losflansch_DN250-PN10-d2730-144041_1001"].geometry
        }
        material={materials["Material.318"]}
        position={[1.17, 11.74, 20.95]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        name="R08474_Losflansch_DN250-PN10-d2730-144041_1004"
        geometry={
          nodes["R08474_Losflansch_DN250-PN10-d2730-144041_1004"].geometry
        }
        material={materials["Material.318"]}
        position={[1.2, 49.32, -1.21]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.86}
      />
      <mesh
        name="Lamellenstopfen_ID_411_111_1001"
        geometry={nodes.Lamellenstopfen_ID_411_111_1001.geometry}
        material={materials["Material.244"]}
        position={[-2.04, 45.89, -24.37]}
        rotation={[Math.PI / 2, 0, 0.7]}
      />
      <mesh
        name="DECKEL_KONISCHPRT(2)_1"
        geometry={nodes["DECKEL_KONISCHPRT(2)_1"].geometry}
        material={materials["Material.435"]}
        position={[1.16, 44.31, -20.1]}
        rotation={[0, 1.57, 2.97]}
      />
      <mesh
        name="R00133_Absperrklappe_Z014-A-HG-DN2501_1"
        geometry={nodes["R00133_Absperrklappe_Z014-A-HG-DN2501_1"].geometry}
        material={nodes["R00133_Absperrklappe_Z014-A-HG-DN2501_1"].material}
        position={[1.48, 12.23, 21.43]}
        rotation={[-Math.PI / 2, 0, 3.14]}
      />
      <mesh
        name="R20004_Fussplatte_60x60x104_2"
        geometry={nodes.R20004_Fussplatte_60x60x104_2.geometry}
        material={nodes.R20004_Fussplatte_60x60x104_2.material}
        position={[15.84, 2.67, 79.9]}
        rotation={[-Math.PI / 2, 0, -1.57]}
      />
      <mesh
        name="R20004_Fussplatte_60x60x104_5"
        geometry={nodes.R20004_Fussplatte_60x60x104_5.geometry}
        material={nodes.R20004_Fussplatte_60x60x104_5.material}
        position={[11.07, 2.67, 76.24]}
        rotation={[-Math.PI / 2, 0, -1.57]}
      />
      <mesh
        name="pied"
        geometry={nodes.pied.geometry}
        material={nodes.pied.material}
        position={[11.07, 3.63, 76.24]}
      />
      <mesh
        name="pied001"
        geometry={nodes.pied001.geometry}
        material={nodes.pied001.material}
        position={[15.84, 3.63, 76.24]}
      />
      <mesh
        name="pied002"
        geometry={nodes.pied002.geometry}
        material={nodes.pied002.material}
        position={[20.62, 3.63, 76.24]}
      />
      <mesh
        name="pied003"
        geometry={nodes.pied003.geometry}
        material={nodes.pied003.material}
        position={[12.04, 3.63, 79.89]}
      />
      <mesh
        name="pied004"
        geometry={nodes.pied004.geometry}
        material={nodes.pied004.material}
        position={[15.84, 3.63, 79.89]}
      />
      <mesh
        name="pied005"
        geometry={nodes.pied005.geometry}
        material={nodes.pied005.material}
        position={[19.64, 3.63, 79.89]}
      />
      <mesh
        name="Floor"
        geometry={nodes.Floor.geometry}
        material={nodes.Floor.material}
        position={[-3.63, 0, 193.55]}
      />
      <mesh
        name="R10523_Drehkolbengeblä_1"
        geometry={nodes.R10523_Drehkolbengeblä_1.geometry}
        material={materials["Material.402"]}
        position={[-8.41, 7.02, 25.73]}
      />
      <mesh
        name="R09870_Kreiselpumpe_NB-125-315-288-AS-F-N-BQQVU1F1P011_2"
        geometry={
          nodes["R09870_Kreiselpumpe_NB-125-315-288-AS-F-N-BQQVU1F1P011_2"]
            .geometry
        }
        material={materials["Material.581"]}
        position={[13.01, 4.32, 59.34]}
        rotation={[0, 1.57, 0]}
      />
      <mesh
        name="R00133_Absperrklappe_Z014-A-HG-DN2501_1001"
        geometry={nodes["R00133_Absperrklappe_Z014-A-HG-DN2501_1001"].geometry}
        material={nodes["R00133_Absperrklappe_Z014-A-HG-DN2501_1001"].material}
        position={[1.48, 4.29, 21.43]}
        rotation={[-Math.PI / 2, 0, 3.14]}
      />
      <mesh
        name="ELEVATION_ZARGE_8410PRT_1"
        geometry={nodes.ELEVATION_ZARGE_8410PRT_1.geometry}
        material={materials["Material.446"]}
        position={[-18.61, 4.51, -10.16]}
        rotation={[0, 1.16, 0]}
      />
      <mesh
        name="R20004_Fussplatte_60x60x104_4"
        geometry={nodes.R20004_Fussplatte_60x60x104_4.geometry}
        material={nodes.R20004_Fussplatte_60x60x104_4.material}
        position={[12.04, 2.67, 79.89]}
        rotation={[-Math.PI / 2, 0, -1.57]}
      />
      <mesh
        name="Cylinder239"
        geometry={nodes.Cylinder239.geometry}
        material={nodes.Cylinder239.material}
        position={[-3.34, 45.59, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder240"
        geometry={nodes.Cylinder240.geometry}
        material={nodes.Cylinder240.material}
        position={[-3.34, 44.19, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder241"
        geometry={nodes.Cylinder241.geometry}
        material={nodes.Cylinder241.material}
        position={[-3.34, 42.78, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder242"
        geometry={nodes.Cylinder242.geometry}
        material={nodes.Cylinder242.material}
        position={[-3.34, 41.38, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder243"
        geometry={nodes.Cylinder243.geometry}
        material={nodes.Cylinder243.material}
        position={[-3.34, 40, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder244"
        geometry={nodes.Cylinder244.geometry}
        material={nodes.Cylinder244.material}
        position={[-3.34, 38.58, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder245"
        geometry={nodes.Cylinder245.geometry}
        material={nodes.Cylinder245.material}
        position={[-3.34, 37.18, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder246"
        geometry={nodes.Cylinder246.geometry}
        material={nodes.Cylinder246.material}
        position={[-3.34, 35.79, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder247"
        geometry={nodes.Cylinder247.geometry}
        material={nodes.Cylinder247.material}
        position={[-3.34, 34.39, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder248"
        geometry={nodes.Cylinder248.geometry}
        material={nodes.Cylinder248.material}
        position={[-3.34, 33, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder249"
        geometry={nodes.Cylinder249.geometry}
        material={nodes.Cylinder249.material}
        position={[-3.34, 31.58, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder250"
        geometry={nodes.Cylinder250.geometry}
        material={nodes.Cylinder250.material}
        position={[-3.34, 30.19, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder251"
        geometry={nodes.Cylinder251.geometry}
        material={nodes.Cylinder251.material}
        position={[-3.34, 28.79, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder252"
        geometry={nodes.Cylinder252.geometry}
        material={nodes.Cylinder252.material}
        position={[-3.34, 27.39, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder253"
        geometry={nodes.Cylinder253.geometry}
        material={nodes.Cylinder253.material}
        position={[-3.34, 25.99, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder254"
        geometry={nodes.Cylinder254.geometry}
        material={nodes.Cylinder254.material}
        position={[-3.34, 24.59, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder255"
        geometry={nodes.Cylinder255.geometry}
        material={nodes.Cylinder255.material}
        position={[-3.34, 23.19, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder256"
        geometry={nodes.Cylinder256.geometry}
        material={nodes.Cylinder256.material}
        position={[-3.34, 21.8, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder257"
        geometry={nodes.Cylinder257.geometry}
        material={nodes.Cylinder257.material}
        position={[-3.34, 20.39, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder258"
        geometry={nodes.Cylinder258.geometry}
        material={nodes.Cylinder258.material}
        position={[-3.34, 18.99, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder259"
        geometry={nodes.Cylinder259.geometry}
        material={nodes.Cylinder259.material}
        position={[-3.34, 17.6, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder260"
        geometry={nodes.Cylinder260.geometry}
        material={nodes.Cylinder260.material}
        position={[-3.34, 16.2, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder261"
        geometry={nodes.Cylinder261.geometry}
        material={nodes.Cylinder261.material}
        position={[-3.34, 14.8, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder262"
        geometry={nodes.Cylinder262.geometry}
        material={nodes.Cylinder262.material}
        position={[-3.34, 13.39, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder263"
        geometry={nodes.Cylinder263.geometry}
        material={nodes.Cylinder263.material}
        position={[-3.34, 12, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder264"
        geometry={nodes.Cylinder264.geometry}
        material={nodes.Cylinder264.material}
        position={[-3.34, 10.59, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder265"
        geometry={nodes.Cylinder265.geometry}
        material={nodes.Cylinder265.material}
        position={[-3.34, 9.2, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder266"
        geometry={nodes.Cylinder266.geometry}
        material={nodes.Cylinder266.material}
        position={[-3.34, 7.8, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder267"
        geometry={nodes.Cylinder267.geometry}
        material={nodes.Cylinder267.material}
        position={[-3.34, 6.39, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder268"
        geometry={nodes.Cylinder268.geometry}
        material={nodes.Cylinder268.material}
        position={[-3.34, 4.99, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder269"
        geometry={nodes.Cylinder269.geometry}
        material={nodes.Cylinder269.material}
        position={[-3.34, 3.61, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cylinder270"
        geometry={nodes.Cylinder270.geometry}
        material={nodes.Cylinder270.material}
        position={[-3.34, 2.19, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="R09871_Kreiselpumpe_NB-65-125-133-A-F2-K-V-BQQVU1S1P011_2001"
        geometry={
          nodes["R09871_Kreiselpumpe_NB-65-125-133-A-F2-K-V-BQQVU1S1P011_2001"]
            .geometry
        }
        material={materials["Material.691"]}
        position={[-6.06, 3.44, 37.96]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="Wä_1001"
        geometry={nodes.Wä_1001.geometry}
        material={materials.Spülbehälter}
        position={[15.84, 8.64, 78.07]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube062"
        geometry={nodes.Cube062.geometry}
        material={nodes.Cube062.material}
        position={[12.92, 2.72, 57.96]}
      />
      <mesh
        name="Cube063"
        geometry={nodes.Cube063.geometry}
        material={nodes.Cube063.material}
        position={[18.82, 2.72, 57.96]}
      />
      <mesh
        name="KASTEN_10_S_0_8490_150ASM_1"
        geometry={nodes.KASTEN_10_S_0_8490_150ASM_1.geometry}
        material={materials["Material.436"]}
        position={[1.26, 43.95, -19.94]}
        rotation={[0, 1.57, -0.17]}
      />
      <mesh
        name="Plane025"
        geometry={nodes.Plane025.geometry}
        material={nodes.Plane025.material}
        position={[95.91, 38.27, -42.08]}
      />
      <mesh
        name="R20004_Fussplatte_60x60x104_1"
        geometry={nodes.R20004_Fussplatte_60x60x104_1.geometry}
        material={nodes.R20004_Fussplatte_60x60x104_1.material}
        position={[15.84, 2.67, 76.25]}
        rotation={[-Math.PI / 2, 0, -1.57]}
      />
      <mesh
        name="R20004_Fussplatte_60x60x104_3"
        geometry={nodes.R20004_Fussplatte_60x60x104_3.geometry}
        material={nodes.R20004_Fussplatte_60x60x104_3.material}
        position={[19.64, 2.67, 79.9]}
        rotation={[-Math.PI / 2, 0, -1.57]}
      />
      <mesh
        name="R20004_Fussplatte_60x60x104_6"
        geometry={nodes.R20004_Fussplatte_60x60x104_6.geometry}
        material={nodes.R20004_Fussplatte_60x60x104_6.material}
        position={[20.62, 2.67, 76.25]}
        rotation={[-Math.PI / 2, 0, -1.57]}
      />
      <mesh
        name="Würfel"
        geometry={nodes.Würfel.geometry}
        material={materials["Material.840"]}
        position={[21.53, 7.17, 68.7]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        name="R06365_Kreiselpumpe_NB-125-200-221-A-F-N-BBQV1_1"
        geometry={
          nodes["R06365_Kreiselpumpe_NB-125-200-221-A-F-N-BBQV1_1"].geometry
        }
        material={materials["Material.403"]}
        position={[-5.95, 3.92, 34.03]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        name="R09871_Kreiselpumpe_NB-65-125-133-A-F2-K-V-BQQVU1S1P011_2"
        geometry={
          nodes["R09871_Kreiselpumpe_NB-65-125-133-A-F2-K-V-BQQVU1S1P011_2"]
            .geometry
        }
        material={materials["Material.691"]}
        position={[11.92, 3.73, 74.17]}
        rotation={[0, 1.57, 0]}
      />
      <mesh
        name="R09870_Kreiselpumpe_NB-125-315-288-AS-F-N-BQQVU1F1P011_2001"
        geometry={
          nodes["R09870_Kreiselpumpe_NB-125-315-288-AS-F-N-BQQVU1F1P011_2001"]
            .geometry
        }
        material={materials["Material.581"]}
        position={[18.9, 4.32, 59.34]}
        rotation={[0, 1.57, 0]}
      />
      <mesh
        name="Plane026"
        geometry={nodes.Plane026.geometry}
        material={nodes.Plane026.material}
      />
      <mesh
        name="Cube064"
        geometry={nodes.Cube064.geometry}
        material={nodes.Cube064.material}
        position={[45.53, 84.98, 172.83]}
      />
      <mesh
        name="R09872_Kreiselpumpe_CRN-32-1-A-F-G-V-HQQV-60Hz1_1"
        geometry={
          nodes["R09872_Kreiselpumpe_CRN-32-1-A-F-G-V-HQQV-60Hz1_1"].geometry
        }
        material={materials["Material.862"]}
        position={[15.33, 3.84, 74.74]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./reception.glb");
