/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";

export default function Model(props) {

  const { nodes, materials } = useGLTF("./reception.glb");
  const openRef = useRef();

  const controls = useControls({
    opacity: {value:1, min:0, max:1, step:0.01}
  })

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Containersockel"
        geometry={nodes.Containersockel.geometry}
        material={materials["Material.937"]}
        position={[15.86, 1.79, 62.41]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Fundament11_1"
        geometry={nodes.Fundament11_1.geometry}
        material={materials["Material.267"]}
        position={[-8.62, 1.7, 30.97]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Fundament_1_remesh001"
        geometry={nodes.Fundament_1_remesh001.geometry}
        material={materials.floor}
        position={[-2.39, 0.43, 19.58]}
      />
      <mesh
        name="CuveSockel"
        geometry={nodes.CuveSockel.geometry}
        material={materials["Material.265"]}
        position={[1.19, 1.58, -1.21]}
      />
      <group name="Cuve" position={[1.19, 33.97, -1.21]}>
        <mesh
          name="Circle001_1"
          geometry={nodes.Circle001_1.geometry}
          material={materials.Cuve}
        />
        <mesh
          name="Circle001_2"
          ref={openRef}
          geometry={nodes.Circle001_2.geometry}
          // material={materials.Open_cuve}
        >
          <meshPhysicalMaterial transparent opacity={controls.opacity}/>
          </mesh>
      </group>
      <mesh
        name="Fundament_1_remesh002"
        geometry={nodes.Fundament_1_remesh002.geometry}
        material={materials["Material.265"]}
        position={[-0.5, 1.74, -38.69]}
      />
      <mesh
        name="Circle002"
        geometry={nodes.Circle002.geometry}
        material={nodes.Circle002.material}
        position={[1.2, 47.68, -1.22]}
      />
      <mesh
        name="Circle"
        geometry={nodes.Circle.geometry}
        material={nodes.Circle.material}
        position={[1.2, 11.74, 19.3]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Circle004"
        geometry={nodes.Circle004.geometry}
        material={nodes.Circle004.material}
        position={[-4.69, 23.31, -23.66]}
      />
      <mesh
        name="Circle005"
        geometry={nodes.Circle005.geometry}
        material={nodes.Circle005.material}
        position={[-2.04, 23.31, -24.37]}
      />
      <mesh
        name="Lamellenstopfen_ID_411_111_1"
        geometry={nodes.Lamellenstopfen_ID_411_111_1.geometry}
        material={materials["Material.244"]}
        position={[-4.69, 45.89, -23.66]}
        rotation={[Math.PI / 2, 0, 0.7]}
      />
      <mesh
        name="Lamellenstopfen_ID_411_111_1001"
        geometry={nodes.Lamellenstopfen_ID_411_111_1001.geometry}
        material={materials["Material.244"]}
        position={[-2.04, 45.89, -24.37]}
        rotation={[Math.PI / 2, 0, 0.7]}
      />
      <mesh
        name="Cylinder270"
        geometry={nodes.Cylinder270.geometry}
        material={nodes.Cylinder270.material}
        position={[-3.34, 2.19, -24.02]}
        rotation={[0, 0.26, -Math.PI / 2]}
      />
      <mesh
        name="Cuve_2"
        geometry={nodes.Cuve_2.geometry}
        material={materials.Cuve}
        position={[1.25, 43.41, -39.74]}
        scale={11.48}
      />
      <mesh
        name="KASTEN_10_S_0_8490_150ASM_1"
        geometry={nodes.KASTEN_10_S_0_8490_150ASM_1.geometry}
        material={materials["Material.436"]}
        position={[1.26, 43.95, -19.94]}
        rotation={[0, 1.57, -0.17]}
      />
      <mesh
        name="DECKEL_KONISCHPRT(2)_1"
        geometry={nodes["DECKEL_KONISCHPRT(2)_1"].geometry}
        material={materials["Material.435"]}
        position={[1.16, 44.31, -20.1]}
        rotation={[0, 1.57, 2.97]}
      />
      <group
        name="Sortie"
        position={[-18.43, 4.54, -9.67]}
        rotation={[0, -0.4, -Math.PI / 2]}
      >
        <mesh
          name="Sortie_1"
          geometry={nodes.Sortie_1.geometry}
          material={materials["Material.446"]}
        />
        <mesh
          name="Sortie_2"
          geometry={nodes.Sortie_2.geometry}
          material={materials["Material.445"]}
        />
      </group>
      <group name="Walls" position={[95.91, 38.27, -42.08]}>
        <mesh
          name="Walls_1"
          geometry={nodes.Walls_1.geometry}
          material={materials.Wall}
        />
        <mesh
          name="Walls_2"
          geometry={nodes.Walls_2.geometry}
          material={materials.glass}
        />
      </group>
      <mesh
        name="Circle001"
        geometry={nodes.Circle001.geometry}
        material={nodes.Circle001.material}
        position={[1.2, 3.78, 19.3]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="pied"
        geometry={nodes.pied.geometry}
        material={nodes.pied.material}
        position={[11.07, 3.63, 76.24]}
      />
      <mesh
        name="pied001"
        geometry={nodes.pied001.geometry}
        material={nodes.pied001.material}
        position={[15.84, 3.63, 76.24]}
      />
      <mesh
        name="pied002"
        geometry={nodes.pied002.geometry}
        material={nodes.pied002.material}
        position={[20.62, 3.63, 76.24]}
      />
      <mesh
        name="pied003"
        geometry={nodes.pied003.geometry}
        material={nodes.pied003.material}
        position={[12.04, 3.63, 79.89]}
      />
      <mesh
        name="pied004"
        geometry={nodes.pied004.geometry}
        material={nodes.pied004.material}
        position={[15.84, 3.63, 79.89]}
      />
      <mesh
        name="pied005"
        geometry={nodes.pied005.geometry}
        material={nodes.pied005.material}
        position={[19.64, 3.63, 79.89]}
      />
      <mesh
        name="Wä_1001"
        geometry={nodes.Wä_1001.geometry}
        material={materials.Spülbehälter}
        position={[15.84, 8.64, 78.07]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Floor"
        geometry={nodes.Floor.geometry}
        material={nodes.Floor.material}
        position={[-3.63, 0, 193.55]}
      />
      <mesh
        name="Würfel"
        geometry={nodes.Würfel.geometry}
        material={materials["Material.840"]}
        position={[21.53, 7.17, 68.7]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        name="Cube062"
        geometry={nodes.Cube062.geometry}
        material={nodes.Cube062.material}
        position={[12.92, 2.72, 57.96]}
      />
      <mesh
        name="Cube063"
        geometry={nodes.Cube063.geometry}
        material={nodes.Cube063.material}
        position={[18.82, 2.72, 57.96]}
      />
      <mesh
        name="R10533_Bogen-90°kurz_d280-KM111_2"
        geometry={nodes["R10533_Bogen-90°kurz_d280-KM111_2"].geometry}
        material={materials["Material.380"]}
        position={[1.13, 11.25, 14.83]}
        rotation={[0, 0, Math.PI / 2]}
      />
      <mesh
        name="R10523_Drehkolbengeblä_1"
        geometry={nodes.R10523_Drehkolbengeblä_1.geometry}
        material={materials["Material.402"]}
        position={[-8.41, 7.02, 25.73]}
      />
      <group name="Toit" position={[43.34, 76.95, 0.89]}>
        <mesh
          name="Toit_1"
          geometry={nodes.Toit_1.geometry}
          material={materials.contour_fenster}
        />
        <mesh
          name="Toit_2"
          geometry={nodes.Toit_2.geometry}
          material={materials.glass}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./reception.glb");
