/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";

export default function Wehrle_cuve(props) {
  const { nodes, materials } = useGLTF("./reception.glb");
  
//   const { animationName } = useControls({
// })

  return (

    <group {...props} dispose={null}>
      <mesh
        name="Fundament_1_remesh001"
        geometry={nodes.Fundament_1_remesh001.geometry}
        material={materials["Material.265"]}
      />
      <mesh
        name="Fundament11_1"
        geometry={nodes.Fundament11_1.geometry}
        material={materials["Material.267"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Containersockel"
        geometry={nodes.Containersockel.geometry}
        material={materials["Material.937"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Circle"
        geometry={nodes.Circle.geometry}
        material={materials["Material.318"]}
      />
      <mesh
        name="Fundament_1_remesh002"
        geometry={nodes.Fundament_1_remesh002.geometry}
        material={materials["Material.265"]}
      />
      <mesh
        name="PE-Platte_U1F1P011_2"
        geometry={nodes["PE-Platte_U1F1P011_2"].geometry}
        material={nodes["PE-Platte_U1F1P011_2"].material}
        rotation={[-Math.PI / 2, 0, -1.57]}
      />
    </group>

  );
}

useGLTF.preload("./reception.glb");
